### ISSUE TITLE
fatal: could not read Password for 'https://github.com': No such device or address

### ISSUE THREAD

**Issue by Otoliths** [tcitry/push-to-master#2]
hi,
how to fix it?
##[warning]Unexpected input 'GITHUB_TOKEN', valid inputs are ['entryPoint', 'args']
Run tcitry/push-to-master@v1.0
with:
  GITHUB_TOKEN: ***
env:
  R_LIBS_USER: /home/runner/work/_temp/Library
TZ: UTC
  NOT_CRAN: true
fatal: could not read Password for 'https://github.com': No such device or address

**Comment by tcitry** [comment]
The action need your GITHUB_TOKEN, or you can custom a secrets ENV TOKEN to fill with your token.

**Comment by tcitry** [comment]
Maybe this can help you, reopen this if you still have problem. https://help.github.com/cn/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line
